package io.github.reiner.examp.mapper;

import org.springframework.stereotype.Repository;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;

import io.github.reiner.examp.model.User;
/**
 * 用户 Dao, generated by MyBatisGenerator
 * @author xh
 * @version 1.0
 * @update 2020-10-19
 **/
 @Repository
public interface UserMapper extends BaseMapper<User> {
}


